spring:
    zipkin:
        baseUrl: http://zipkin/
        locator.discovery.enabled: true

spring.sleuth.rxjava.schedulers.hook.enabled: false

eureka.instance.metadataMap.cluster: ${name:gateway}

info:
    project:
        version: 0.0.1-SNAPSHOT
        title: user
        description: user service
